/**
 * Bilibili 字符串资源 — 对应 AOSP res/values/strings.xml
 *
 * 中文为基线；英文覆盖见 strings.en.ts。
 * 模板占位符使用 {n} / {name} 等，消费端用 .replace('{n}', ...) 填充。
 */
export const strings = {
  // ============================================================================
  // [common] - 通用高频字符串
  // ============================================================================
  common_cancel: '取消',
  common_confirm: '确定',
  common_save: '保存',
  common_done: '完成',
  common_edit: '编辑',
  common_back: '返回',
  common_close: '关闭',
  common_follow: '关注',
  common_follow_plus: '+ 关注',
  common_following: '已关注',
  common_view_more: '查看更多',
  common_fans: '粉丝',
  common_likes_received: '获赞',
  common_ad: '广告',
  common_up_badge: 'UP主',
  common_play_all: '播放全部',
  common_charge: '充电',
  common_unknown: '未知',
  menu_add_special: '加入特别关注',
  menu_set_group: '设置分组',
  menu_unfollow: '取消关注',
  sign_empty: '这个人很懒，什么都没有写',
  stat_item_count: '{n}个内容',
  stat_plays: '播放',
  stat_danmaku: '弹幕',
  fav_public: '公开',
  fav_private: '私密',
  ip_location_label: 'IP属地',

  // 时间
  time_just_now: '刚刚',
  time_minutes_ago: '{n}分钟前',
  time_hours_ago: '{n}小时前',
  time_days_ago: '{n}天前',
  time_today: '今天',
  time_yesterday: '昨天',
  date_md: '{m}月{d}日',
  date_ymd: '{y}年{m}月{d}日',
  date_ymd_hm: '{y}年{m}月{d}日 {hm}',
  date_ym: '{y}年{m}月',
  date_year: '{y}年',
  date_mdw: '{m}月{d}日{w}',
  week_prefix: '周{w}',
  week_sun: '日',
  week_mon: '一',
  week_tue: '二',
  week_wed: '三',
  week_thu: '四',
  week_fri: '五',
  week_sat: '六',

  // ============================================================================
  // [tabbar] - 底部导航（BilibiliApp）
  // ============================================================================
  tabbar_home: '首页',
  tabbar_following: '关注',
  tabbar_publish: '发布',
  tabbar_shop: '会员购',
  tabbar_me: '我的',

  // ============================================================================
  // [home] - 首页
  // ============================================================================
  tab_live: '直播',
  tab_recommended: '推荐',
  tab_hot: '热门',
  tab_anime: '动画',
  tab_film_tv: '影视',
  tab_new_year: '跨年',
  home_tab_new_journey: '新征程',
  home_newyear_coming: '跨年晚会 敬请期待',
  home_search_hint: '梦幻情侣',
  home_mock_like_count: '1.4万',

  // 首页-直播 Tab
  live_badge: '直播中',
  live_cat_recommend: '推荐',
  live_cat_popularity: '人气',
  live_cat_beauty: '颜值',
  live_cat_lol: '英雄联盟',
  live_cat_vtuber: '虚拟主播',
  live_cat_honor: '王者荣耀',
  live_cat_single: '单机',
  live_cat_radio: '电台',

  // 首页-热门 Tab
  hot_rankings: '排行榜',
  hot_weekly: '每周必看',
  hot_gala: '跨年晚会',
  hot_must_watch: '入站必刷',
  hot_report: '年度报告',
  hot_badge_million: '百万播放',
  hot_badge_shared: '很多人分享',
  hot_badge_energy: '高能',
  hot_views: '观看',

  // 首页-动画 Tab
  anime_hot_rankings: '热门排行榜',
  anime_more_rankings: '更多榜单 >',

  // 首页-影视 Tab
  movie_picked: '猜你想追',
  movie_watchlist: '我的追剧 >',
  movie_streaming: '正在热播',

  // ============================================================================
  // [shop] - 会员购
  // ============================================================================
  shop_figure: '手办雕像',
  shop_blind_box: '盲盒',
  shop_event_show: '漫展演出',
  shop_all_categories: '分类',
  shop_title: '会员购',
  shop_search_hint: '灵能百分百',
  shop_search: '搜索',
  shop_orders: '我的订单',
  shop_cart: '购物车',
  shop_coupons: '优惠券',
  shop_favorites: '商品收藏',
  shop_history: '商品足迹',
  shop_owned_label: '自营',
  shop_price_label: '新人价',
  shop_price_suffix: '起',
  shop_coupon_pack: '新人券包',
  shop_coupon_desc: '新人包邮1元起',
  shop_use_now: '去使用',
  shop_product_1: 'BEMOE 初音未来 2025新春系列',
  shop_product_2: '会员购爆款周边 抽盲盒赢黄金',
  shop_product_3: 'FURYU 碧蓝档案 优香 手办',
  shop_product_4: 'APEX 英雄 动力小子',
  shop_product_5: '原神 刻晴 霆霓快雨',
  shop_product_6: '明日方舟 罗德岛 战术背包',

  // ============================================================================
  // [search] - 搜索页
  // ============================================================================
  search_action: '搜索',
  search_placeholder: '10年暴跌180亿! 营养快线 为啥...',
  search_hot_title: 'bilibili热搜',
  search_full_list: '完整榜单',
  search_tag_new: '新',
  search_tag_hot: '热',
  search_tag_meme: '梗',
  search_history: '搜索历史',
  search_discovery: '搜索发现',
  search_tab_comprehensive: '综合',
  search_tab_anime: '番剧',
  search_tab_live: '直播',
  search_tab_user: '用户',
  search_tab_movie: '影视',
  search_tab_article: '图文',
  search_participating: '{n}人参与',
  search_mock_participants: '1.2万',
  search_score_suffix: '分',
  search_produce_badge: '出品',
  search_region_cn: '中国大陆',
  search_tags_anime: '原创/热血/奇幻/战斗',
  search_tags_movie: '剧情/冒险/科幻',
  search_watch_now: '立即观看',
  search_follow_anime: '追番',
  search_following_anime: '已追番',
  search_follow_drama: '追剧',
  search_following_drama: '已追剧',
  search_fans_count: '{n}粉丝',
  search_videos_count: '{n}个视频',
  search_up_desc: 'bilibili 知名UP主',
  search_view_all_videos: '查看全部{n}个视频',
  search_chip_all: '全部',
  search_chip_movie: '电影',
  search_chip_song: '歌曲',
  search_chip_nexus: '奈克瑟斯',
  search_chip_yan: '燕双鹰',
  search_empty_anime: '没有找到相关番剧',
  search_empty_movie: '没有找到相关影视',
  search_empty_user: '没有找到相关用户',
  search_empty_video: '没有找到相关视频',

  // ============================================================================
  // [video] - 视频详情页
  // ============================================================================
  video_tab_intro: '简介',
  video_tab_comments: '评论',
  video_send_danmaku: '点我发弹幕',
  video_danmaku_glyph: '弹',
  video_fans_count: '{n}粉丝',
  video_videos_count: '{n}视频',
  video_watching_count: '{n}人正在看',
  video_no_reprint: '未经作者授权禁止转载',
  video_ad_promo: '不会做的题？千问帮你看看',
  video_ad_meta: '广告 · 22.8万播放',
  video_interested: '你可能感兴趣',
  video_related: '相关推荐',
  video_related_meta: '{a}播放 · {b}弹幕',
  action_like: '点赞',
  action_dislike: '不喜欢',
  action_coin: '投币',
  action_fav: '收藏',
  action_share: '分享',
  video_play: '播放',
  video_pause: '暂停',
  video_fullscreen: '全屏',
  comment_expand: '展开',
  comment_collapse: '收起',
  comment_reply: '回复',
  comment_reply_count: '共{n}条回复',
  comment_hot: '热门评论',
  comment_new: '最新评论',
  comment_sort_hot: '按热度',
  comment_sort_time: '按时间',
  comment_empty: '暂无评论',
  comment_placeholder: '万水千山总是情，评论两句行不行',
  vip_glyph: '大',
  coin_glyph: '币',
  coin_one: '1 硬币',
  coin_two: '2 硬币',
  coin_submit_hint: '上划或点击22娘投硬币',
  coin_balance: '硬币余额：{n}',
  coin_also_like: '同时点赞内容',
  coin_how: '如何获取硬币？',
  coin_success: '投币成功',
  mascot_alt: '22娘',

  // store toast（state.ts）
  toast_coin_limit: '投硬币失败~超过投币上限啦~',
  toast_coin_insufficient: '硬币不足',
  toast_coin_insufficient_like: '硬币不足，仅点赞收藏',
  toast_triple_success: '三连成功',
  user_fallback_name: '用户{mid}',

  // ============================================================================
  // [following] - 关注页
  // ============================================================================
  following_title: '关注',
  following_tab_all: '全部',
  following_tab_video: '视频',
  following_most_visited: '最常访问',
  following_more: '更多',
  following_anime_updates: '我的追番·追剧',
  following_view_all: '全部',
  following_uploaded_video: '投稿了视频',
  following_episode_update: '更新至第{n}话',
  following_empty_title: '你还没有关注过UP主哦',
  following_empty_desc: '关注更多的UP主，精彩内容不错过',
  following_recommended: '猜你喜欢的UP主',
  following_recommended_up: '推荐UP主',

  // ============================================================================
  // [me] - 我的页
  // ============================================================================
  me_challenge: '挑战转正答题',
  me_set_nickname: '点击设置昵称',
  me_vip: '大会员',
  me_regular_member: '注册会员',
  me_b_coins: 'B币',
  me_coins: '硬币',
  me_space: '空间',
  me_dynamics: '动态',
  me_following: '关注',
  me_fans: '粉丝',
  me_upgrade_vip: '成为大会员',
  me_vip_center: '会员中心',
  me_vip_desc: '解锁线下专属权益',
  me_offline: '离线缓存',
  me_history: '历史记录',
  me_favorites: '我的收藏',
  me_watch_later: '稍后再看',
  me_creator_title: '发布你的第一个视频',
  me_creator_desc: '领限定头像挂件，赢活动奖金',
  me_creator_action: '有奖发布',
  me_my_services: '我的服务',
  me_courses: '我的课程',
  me_data_free: '免流量服务',
  me_dress_up: '个性装扮',
  me_wallet: '我的钱包',
  me_games: '游戏中心',
  me_shop_orders: '会员购订单',
  me_lives: '我的直播',
  me_manga: '漫画',
  me_promote: '必火推广',
  me_create_center: '创作中心',
  me_community: '社区中心',
  me_charity: '公益',
  me_energy: '能量加油站',
  me_coupons: '次元消费券',
  me_report: '年度报告',
  me_more_services: '更多服务',
  me_contact: '联系客服',
  me_audio: '听视频',
  me_guardian: '未成年人守护',
  me_settings: '设置',

  // ============================================================================
  // [space] - 个人空间
  // ============================================================================
  space_tab_home: '主页',
  space_tab_works: '投稿',
  space_tab_fav: '收藏',
  space_tab_anime: '追番',
  space_edit_profile: '编辑资料',
  space_vip_badge: '大会员',
  space_fan_medal: '粉丝勋章',
  space_achieve_medal: '成就勋章',
  space_detail: '详情',
  space_collapse: '收起',
  space_sign_fallback: '你好',
  space_add_school: '添加学校信息',
  space_fav_section: '收藏',
  space_anime_section: '追番',
  space_chasing: '在追',
  space_publish_first: '发布第一个视频，领新人福利',
  space_upload_btn: '我要投稿',
  space_creator_reward: '去创作中心领奖',
  space_my_folders: '我创建的收藏夹',
  space_my_subscriptions: '我的收藏与订阅',
  recent_likes_title: '最近点赞的视频',
  recent_likes_end: '╮( 3 )╭  再怎么找也没有啦',

  // ============================================================================
  // [up] - UP 主页（UserProfilePage）
  // ============================================================================
  up_loading: '正在获取用户信息...',
  up_tab_home: '主页',
  up_tab_dynamic: '动态',
  up_tab_works: '投稿',
  up_tab_shop: '小店',
  up_verify_prefix: 'bilibili UP主认证: ',
  up_not_live: 'TA现在并没有直播，去订阅TA的直播',
  up_videos_section: '视频',
  up_uploaded_video: '投稿了视频',
  up_sort_latest: '最新发布',
  up_no_goods: '暂无商品',

  // ============================================================================
  // [relation] - 关注/粉丝列表
  // ============================================================================
  rel_title: '我的好友',
  rel_tab_follow: '关注',
  rel_tab_fans: '粉丝',
  rel_search_follow: '搜索我的关注',
  rel_search_fans: '搜索我的粉丝',
  rel_my_follow: '我的关注',
  rel_my_fans: '我的粉丝',
  rel_count_people: '{n}人',
  rel_recent_visit: '最近访问',
  rel_empty_follow: '暂无关注',
  rel_empty_fans: '暂无粉丝',

  // ============================================================================
  // [fav] - 收藏
  // ============================================================================
  fav_title: '收藏',
  fav_chase: '追更',
  fav_tab_folders: '收藏夹',
  fav_tab_all: '全部',
  fav_tab_video: '视频',
  fav_tab_article: '图文',
  fav_empty: '暂无收藏内容',
  fav_empty_article: '暂无图文收藏',
  fav_folder_default: '收藏夹',
  fav_folder_creator: '创建者: {name}',
  fav_detail_creator: '创建者：{name}',
  fav_folder_empty: '收藏夹为空',
  fav_no_cover: '无封面',
  fav_added_default: '已加入"默认收藏夹"',
  fav_modify: '修改收藏夹',
  fav_watch_later: '添加到稍后再看',
  fav_choose_folder: '选择收藏夹',
  fav_new_folder: '新建收藏夹',
  fav_create_title: '创建',
  fav_create_cover: '封面',
  fav_create_name: '名称',
  fav_create_name_placeholder: '名称',
  fav_create_desc: '简介',
  fav_create_desc_placeholder: '可填写简介',
  fav_create_public: '公开',

  // ============================================================================
  // [ranking] - 排行榜
  // ============================================================================
  ranking_title: '全区排行榜',
  ranking_danmaku_count: '{n}弹幕',
  ranking_bili_prefix: '哔哩哔哩{p}',
  ranking_no_cover: '暂无封面',
  ranking_empty: '暂无数据',

  // ============================================================================
  // [partitions] - 分区页
  // ============================================================================
  partitions_title: '分区',
  partitions_quick: '快捷访问',
  partitions_edit: '编辑',
  partitions_all: '全部分区',
  partitions_recommend: '推荐分区/服务',
  partition_fallback: '分区',
  partition_empty: '暂无相关视频',

  // ============================================================================
  // [profile] - 账号资料
  // ============================================================================
  pe_title: '账号资料',
  pe_avatar: '头像',
  pe_nickname: '昵称',
  pe_gender: '性别',
  pe_birthday: '出生年月',
  pe_birthday_hint: '生日当天会收到祝福',
  pe_sign: '个性签名',
  pe_sign_hint: '这个人很神秘，什么都没有写',
  pe_school: '学校',
  pe_school_hint: '填写学校发现更多校友~',
  pe_pendant: '头像挂件',
  pe_qr: '二维码名片',
  pe_auth: '哔哩哔哩认证',
  gender_male: '男',
  gender_female: '女',
  gender_secret: '保密',
  pe_name_title: '修改昵称',
  pe_name_placeholder: '请输入新昵称',
  pe_name_cost: '修改昵称需要消耗6枚硬币',
  pe_sign_title: '修改个性签名',
  pe_sign_placeholder: '请输入新个性签名',

  // ============================================================================
  // [school] - 学校信息
  // ============================================================================
  school_title: '学校信息',
  school_select: '选择学校',
  school_year: '入学年份',
  school_year_optional: '选填',
  school_edit_limit: '每30天内仅可修改一次',
  school_delete: '删除学校信息',
  school_search_placeholder: '搜索学校',
  school_success: '恭喜你成功加入{school}校园',
  school_invite: '去邀请更多校友',

  // ============================================================================
  // [vip] - 大会员购买页
  // ============================================================================
  vip_title: '成为大会员',
  vip_expire: '大会员：有效期至{date}',
  vip_not_vip: '你还不是大会员，开通福利多多 ①',
  vip_device_scope: '手机/电脑/Pad上可用',
  vip_switch_plan: '切换普通套餐 ⇌',
  vip_pkg_year_auto: '连续包年',
  vip_pkg_year_super: '超大连续包年',
  vip_pkg_month_auto: '连续包月',
  vip_pkg_quarter_auto: '连续包季',
  vip_pkg_quarter_super: '超大连续包季',
  vip_badge_gift: '赠',
  vip_badge_flash: '限时红包',
  vip_discount: '已优惠¥{n}',
  vip_gift_month: '本次送网易严选Pro纯享会员月卡',
  vip_renew_note: '每月按{n}元自动续费，可随时取消自动续费',
  vip_voucher: '代金券',
  vip_no_voucher: '不使用代金券 >',
  vip_use_prefix: '使用',
  vip_joint: '联合会员',
  vip_see_more: '查看更多 >',
  vip_agreement: '开通前请阅读《大会员服务协议》《大会员自动续费服务规则》',
  vip_confirm_pay: '确认协议并支付 ¥{n}',
  vip_payment_title: '支付方式',
  vip_alipay: '支付宝',
  vip_wechat: '微信支付',
  vip_huabei: '花呗',
  vip_pay_agreement_desc: '，已阅读并同意《付款授权服务协议》，开通后到期前24小时将自动发起续费，可随时取消自动续费',
  vip_pay_agreement_full: '已阅读并同意《付款授权服务协议》，开通后到期前24小时将自动发起续费，可随时取消自动续费',
  vip_select_wechat: '请选择微信支付以体验完整流程',

  // ============================================================================
  // [settings] - 设置主页
  // ============================================================================
  settings_title: '设置',
  settings_timer_off: '不开启',
  settings_timer_on: '已开启',
  settings_sleep_on: '已提醒',
  settings_sleep_off: '不提醒',
  settings_account_profile: '账号资料',
  settings_security: '安全隐私',
  settings_shipping: '收货信息',
  settings_language: '语言',
  settings_splash: '开屏画面设置',
  settings_recommend: '首页推荐设置',
  settings_recommend_subtitle: '双列/Wi-Fi/免流/移动网络下自动播放',
  settings_avatar_entry: '首页头像入口设置',
  settings_playback: '播放设置',
  settings_offline: '离线设置',
  settings_chase: '追番/追剧设置',
  settings_push: '推送设置',
  settings_messages: '消息设置',
  settings_harass: '防骚扰和互动人群设置',
  settings_downloads: '下载管理',
  settings_storage: '清理存储空间',
  settings_other: '其他设置',
  settings_timer: '定时关闭',
  settings_sleep: '睡眠提醒',
  settings_dark: '深色设置',
  settings_support: '我的客服',
  settings_about: '关于哔哩哔哩',
  settings_business: '商务合作',
  settings_terms: '用户协议',
  settings_privacy: '隐私政策',
  settings_privacy_permissions: '隐私权限设置',
  settings_collection_list: '个人信息收集清单',
  settings_sharing_list: '第三方信息共享清单',
  settings_basic_privacy: '哔哩哔哩（基本功能）隐私政策',
  settings_switch_account: '账号切换',
  settings_logout: '退出登录',

  // 通用设置选项
  opt_all: '所有人',
  opt_following: '关注的人',
  opt_none: '不接收任何消息提醒',
  opt_receive: '接收提醒',
  opt_never: '永不提醒',
  opt_receive_msg: '接收消息',
  opt_not_receive: '不接收',
  opt_on: '开启',
  opt_off: '关闭',

  // ============================================================================
  // [settings.push] - 推送设置
  // ============================================================================
  sp_title: '推送设置',
  sp_master: '接收消息通知总开关 [已开启]',
  sp_master_sub: '请在您设备的「设置-通知」中,选择「哔哩哔哩」进行修改',
  sp_dnd: '消息免打扰',
  sp_dnd_sub: '开启后,免打扰时间内将不会收到推送消息',
  sp_sec_interact: '互动通知',
  sp_like: '点赞',
  sp_comment: '评论',
  sp_sec_pm: '私信通知',
  sp_chat: '聊天消息',
  sp_sec_follow: '关注通知',
  sp_follow_up: '关注up主的更新提醒',
  sp_sec_content: '内容推荐',
  sp_recommend: '推荐可能感兴趣的内容',
  sp_hot: '热点',
  sp_activity: '活动',
  sp_sec_sub: '订阅/预约通知',
  sp_chase: '追番追剧更新提醒',
  sp_live: '直播提醒',
  sp_collection: '订阅合集更新提醒',
  sp_search: '搜索内容更新提醒',
  sp_other_sub: '其他订阅/预约提醒',
  sp_sec_helper: 'UP主小助手',
  sp_upload: '投稿服务通知',
  sp_sec_service: '服务通知',
  sp_logistics: '物流与订单通知',
  sp_value: '增值服务通知',
  sp_sec_other: '其他通知',
  sp_security: '账号安全通知',
  sp_other: '其他通知',
  sp_sec_banner: 'APP内通知横幅',
  sp_banner: '应用内顶部横幅提醒',
  sp_banner_sub: '开启后，应用使用期间会收到推送通知',

  // ============================================================================
  // [settings.message] - 消息设置
  // ============================================================================
  sm_title: '消息设置',
  sm_sec_notify: '消息提醒',
  sm_notify: '消息提醒',
  sm_notify_sub: '关闭后，APP首页将不再进行数字提醒',
  sm_sec_receive: '消息接收设置',
  sm_smart_block: '私信智能拦截',
  sm_smart_block_sub: '开启后，将自动拦截疑似骚扰和不良的会话',
  sm_block_words: '消息屏蔽词',
  sm_block_words_sub: '添加后，将不再接受包含屏蔽词的消息',
  sm_sec_interact: '互动通知',
  sm_reply_at: '回复与@',
  sm_reply_at_sub: '你将收到这些人的评论、弹幕等通知提醒',
  sm_like: '收到喜欢',
  sm_like_sub: '是否接收点赞等通知提醒',
  sm_fan: '新增粉丝',
  sm_fan_sub: '是否接收新增粉丝通知提醒',
  sm_sec_support: '应援团和未关注人',
  sm_support: '应援团消息',
  sm_unfollow: '未关注人消息',
  sm_sec_contacts: '联系人',
  sm_blacklist: '黑名单',
  smr_title: '回复与@消息提醒',
  sml_title: '收到喜欢消息提醒',
  smf_title: '新增粉丝消息提醒',

  // ============================================================================
  // [settings.harass] - 防骚扰
  // ============================================================================
  sh_title: '防骚扰和互动人群设置',
  sh_sec_short: '短期防护',
  sh_onekey: '一键防骚扰',
  sh_onekey_sub: '开启后,特定时间内只接收选定人群的私信、弹幕、评论,并不再接收@消息。',
  sh_sec_long: '长期防护',
  sh_comment: '谁可以发评论',
  sh_danmaku: '谁可以发弹幕',
  sh_pm: '谁可以发私信',
  sh_opt_7days: '关注我7天以上的人',
  sh_opt_following: '我关注的人',

  // ============================================================================
  // [settings.recommend] - 首页推荐设置
  // ============================================================================
  sr_title: '首页推荐设置',
  sr_sec_mode: '首页视频播放模式',
  sr_portrait: '竖屏模式',
  sr_portrait_sub: '默认用竖屏模式播放视频',
  sr_auto: '自动模式',
  sr_auto_sub: '根据视频类型自动选择播放模式',
  sr_sec_autoplay: '首页自动播放',
  sr_opt_all: 'Wi-Fi/免流/移动网络下自动播放',
  sr_opt_wifi: '仅Wi-Fi下自动播放',
  sr_opt_off: '关闭自动播放',
  sr_sec_sound: '大卡默认声音(重启后生效)',
  sr_sound_on: '默认打开',
  sr_sound_off: '默认静音',
  sr_sec_refresh: '首页推荐自动刷新',
  sr_column: '首页单双列切换',

  // ============================================================================
  // [settings.storage] - 清理存储空间
  // ============================================================================
  st_title: '清理存储空间',
  st_base: 'App 基础组件库',
  st_image: '图片缓存、消息记录',
  st_other: '其它缓存文件',
  st_account: '账号、登录信息',
  st_offline: '离线缓存的视频文件',
  st_webview: 'webview的缓存文件',
  st_game: '游戏预下载资源包',
  st_clean: '清理选中项目',

  // ============================================================================
  // [settings.playback] - 播放设置
  // ============================================================================
  spb_title: '播放设置',
  spb_autoplay: '自动播放设置',
  spb_portrait: '竖屏模式设置',
  spb_pip: '小窗播放/后台听视频设置',
  spb_danmaku: '弹幕/字幕设置',
  spb_quality: '清晰度设置',
  spb_other: '其他设置',
  spa_data: '流量网络下自动播放',
  spa_detail: '视频详情页直接播放',
  spa_detail_sub: '进入视频详情页后自动播放视频',
  spa_fullscreen: '视频详情页直接全屏',
  spa_fullscreen_sub: '进入视频详情页后自动全屏播放视频',
  spa_feed: '动态/活动页单列视频是否自动播放',
  spa_feed_sub: '开启自动播放',
  spa_home: '首页自动播放',
  saf_hint: '选择后,将影响所有列表场景下的视频播放',
  saf_opt_on: '开启自动播放',
  saf_opt_wifi: '仅WiFi/免流下自动播放',
  spp_label: '竖屏视频全屏用竖屏模式播放',
  spp_sub: '全屏后可以上下滑视频',
  pip_sec_pip: '小窗播放设置',
  pip_out: '应用外自动小窗播放',
  pip_out_sub: '切出APP时自动出小窗，继续播放视频/直播',
  pip_in: '应用内自动小窗播放',
  pip_in_sub: '切到APP内其他页面时出小窗，继续播放视频',
  pip_size: '小窗默认尺寸',
  pip_size_sub: '可双击小窗，调整尺寸大小',
  pip_sec_bg: '后台听视频设置',
  pip_bg: '后台听视频',
  pip_bg_sub: '锁屏或切到后台时，继续播放视频声音',
  pip_bg_series: '后台听视频时，自动连播相关视频',
  sd_sec_danmaku: '弹幕设置',
  sd_memory: '记忆弹幕开关状态',
  sd_memory_sub: '弹幕开关状态变化将同步至此设备的所有视频',
  sd_quick: '弹幕快捷选择功能',
  sd_quick_sub: '点击弹幕可进行点赞、复制等操作',
  sd_sec_subtitle: '字幕设置',
  sd_feedback: '字幕反馈模式',
  sd_feedback_sub: '开启可点击字幕进行反馈',
  sd_drag: '字幕拖拽',
  sd_drag_sub: '开启可进行字幕拖拽',
  sq_hdr: '优先播放HDR清晰度',
  sq_hdr_sub: '大会员且设备支持时优先选中',
  spo_fullscreen_count: '全屏播放面板展示同时在看人数',
  spo_gravity: '启用重力感应旋屏',
  spo_gravity_sub: '可通过重力感应切换半屏/全屏播放器',
  spo_sec_volume: '音量均衡',
  spo_vol_standard: '标准模式',
  spo_vol_standard_sub: '自动平衡不同视频间的音量大小',
  spo_vol_high: '高动态模式',
  spo_vol_high_sub: '保留更多声音细节,但音量更小',
  spo_eye: '护眼模式',
  spo_color: '色觉辅助',
  spo_https: '启用https播放',
  spo_https_sub: '启用更安全',

  // ============================================================================
  // [settings.avatarEntry] - 首页头像入口
  // ============================================================================
  sa_title: '首页头像入口设置',
  sa_sec_jump: '首页头像入口跳转设置',
  sa_recent: '最近/看视频/听视频',
  sa_recent_sub: '点击首页左上角头像入口跳转至最近等内容',
  sa_watch: '看视频',
  sa_watch_sub: '关闭后不展示看视频入口',
  sa_listen: '听视频',
  sa_listen_sub: '关闭后不展示听视频入口',
  sa_me: '我的',
  sa_me_sub: '点击首页左上角头像入口跳转至我的页',
  sa_sec_quick: '最近页快捷功能设置',
  sa_offline: '离线缓存',
  sa_history: '历史记录',
  sa_fav: '我的收藏',
  sa_later: '稍后再看',
  sa_add: '添加',

  // ============================================================================
  // [settings.misc] - 追番/离线/语言/应援团/未关注人/定时/睡眠/水印/图片质量/其他
  // ============================================================================
  sc_title: '追番/追剧设置',
  sc_xianxiu: '修仙模式',
  sc_xianxiu_sub: '开启后深夜0点-6点的动画将在前一天展示',
  sc_sec_preview: '修仙模式预览',
  sc_preview_hint: '修仙模式 显示次日0-6点番剧',
  so_title: '离线设置',
  so_auto: '自动下载',
  so_auto_sub: '自动开始未完成的下载任务',
  so_diagnosis: '离线诊断',
  so_sdcard: '外置存储卡测试',
  sl_title: '语言',
  sl_sec: 'App 语言',
  ssu_title: '应援团',
  ssu_receive: '接收应援团消息',
  ssu_receive_sub: '应援团消息提醒',
  ssu_collapse: '收起应援团消息',
  ssu_collapse_sub: '开启后,应援团消息将被折叠在我的应援团内',
  ssu_sec_guide: '应援团攻略',
  ssu_join: '加入应援团攻略',
  sun_title: '未关注人消息',
  sun_sec: '未关注人消息提醒',
  sun_collapse: '收起未关注人消息',
  sun_collapse_sub: '开启后,未关注人消息将被折叠在未关注人消息内',
  sti_title: '定时关闭',
  sti_hint: '计时结束后，将进行提醒',
  sti_off: '不开启',
  sti_15: '15分钟',
  sti_30: '30分钟',
  sti_60: '60分钟',
  sti_custom: '自定义',
  ssl_title: '睡眠提醒',
  ssl_label: '睡眠提醒',
  ssl_sub: '开启后在睡眠时间将进行提醒',
  sw_title: '图片水印设置',
  sw_hint: '开启后,将为动态和评论发布的图片添加水印',
  sw_off: '不启用',
  sw_center: '图片中部',
  sw_br: '图片右下角',
  si_title: '默认图片质量',
  si_clear: '清晰',
  si_clear_sub: '清晰 (质量高,图片更清晰)',
  si_normal: '普通',
  si_normal_sub: '普通 (流量少,速度加载快)',
  si_auto: '自动',
  si_auto_sub: '自动 (wifi下使用清晰,流量下使用普通)',
  sot_title: '其他设置',
  sot_wifi_pkg: 'WIFI下自动准备安装包',
  sot_wifi_pkg_sub: '在WIFI下自动帮你下载好最新安装包',
  sot_clipboard: '剪贴板自动跳转',
  sot_clipboard_sub: '自动帮你跳转到已复制的内容',
  sot_screenshot: '截屏快捷分享',
  sot_screenshot_sub: '关闭后,在视频播放页/动态详情页截屏时,不再出现快捷分享引导。',
} as const;

export type StringKey = keyof typeof strings;
