/**
 * Bilibili English string resources
 * Corresponds to strings.ts (Chinese source)
 */
import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  // ============================================================================
  // [common]
  // ============================================================================
  common_cancel: 'Cancel',
  common_confirm: 'OK',
  common_save: 'Save',
  common_done: 'Done',
  common_edit: 'Edit',
  common_back: 'Back',
  common_close: 'Close',
  common_follow: 'Follow',
  common_follow_plus: '+ Follow',
  common_following: 'Following',
  common_view_more: 'View more',
  common_fans: 'Followers',
  common_likes_received: 'Likes',
  common_ad: 'Ad',
  common_up_badge: 'Creator',
  common_play_all: 'Play all',
  common_charge: 'Boost',
  common_unknown: 'Unknown',
  menu_add_special: 'Add to special follows',
  menu_set_group: 'Set group',
  menu_unfollow: 'Unfollow',
  sign_empty: 'This user is lazy and left nothing here',
  stat_item_count: '{n} items',
  stat_plays: 'views',
  stat_danmaku: 'danmaku',
  fav_public: 'Public',
  fav_private: 'Private',
  ip_location_label: 'IP region',

  time_just_now: 'Just now',
  time_minutes_ago: '{n}m ago',
  time_hours_ago: '{n}h ago',
  time_days_ago: '{n}d ago',
  time_today: 'Today',
  time_yesterday: 'Yesterday',
  date_md: '{m}/{d}',
  date_ymd: '{m}/{d}/{y}',
  date_ymd_hm: '{m}/{d}/{y} {hm}',
  date_ym: '{m}/{y}',
  date_year: '{y}',
  date_mdw: '{m}/{d} {w}',
  week_prefix: '{w}',
  week_sun: 'Sun',
  week_mon: 'Mon',
  week_tue: 'Tue',
  week_wed: 'Wed',
  week_thu: 'Thu',
  week_fri: 'Fri',
  week_sat: 'Sat',

  // ============================================================================
  // [tabbar]
  // ============================================================================
  tabbar_home: 'Home',
  tabbar_following: 'Following',
  tabbar_publish: 'Post',
  tabbar_shop: 'Shop',
  tabbar_me: 'Me',

  // ============================================================================
  // [home]
  // ============================================================================
  tab_live: 'Live',
  tab_recommended: 'For You',
  tab_hot: 'Trending',
  tab_anime: 'Anime',
  tab_film_tv: 'Films & TV',
  tab_new_year: 'New Year',
  home_tab_new_journey: 'New Era',
  home_newyear_coming: 'New Year special coming soon',
  home_search_hint: 'Perfect Match',
  home_mock_like_count: '14K',

  live_badge: 'LIVE',
  live_cat_recommend: 'For You',
  live_cat_popularity: 'Popular',
  live_cat_beauty: 'Beauty',
  live_cat_lol: 'League of Legends',
  live_cat_vtuber: 'VTubers',
  live_cat_honor: 'Honor of Kings',
  live_cat_single: 'Single-player',
  live_cat_radio: 'Radio',

  hot_rankings: 'Rankings',
  hot_weekly: 'Weekly picks',
  hot_gala: 'New Year gala',
  hot_must_watch: 'Must-watch',
  hot_report: 'Year in review',
  hot_badge_million: '1M views',
  hot_badge_shared: 'Shared a lot',
  hot_badge_energy: 'High energy',
  hot_views: 'views',

  anime_hot_rankings: 'Top rankings',
  anime_more_rankings: 'More rankings >',

  movie_picked: 'Picked for you',
  movie_watchlist: 'My watchlist >',
  movie_streaming: 'Now streaming',

  // ============================================================================
  // [shop]
  // ============================================================================
  shop_figure: 'Figures & Statues',
  shop_blind_box: 'Blind Box',
  shop_event_show: 'Events & Shows',
  shop_all_categories: 'Categories',
  shop_title: 'Shop',
  shop_search_hint: 'Mob Psycho 100',
  shop_search: 'Search',
  shop_orders: 'Orders',
  shop_cart: 'Cart',
  shop_coupons: 'Coupons',
  shop_favorites: 'Saved items',
  shop_history: 'Footprints',
  shop_owned_label: 'Official',
  shop_price_label: 'New-user price',
  shop_price_suffix: '+',
  shop_coupon_pack: 'New user coupons',
  shop_coupon_desc: 'Starting at ¥1 with free shipping',
  shop_use_now: 'Use now',
  shop_product_1: 'BEMOE Hatsune Miku 2025 Spring Collection',
  shop_product_2: 'Best-selling merch blind box event',
  shop_product_3: 'FURYU Blue Archive Yuuka figure',
  shop_product_4: 'APEX Legends Octane collectible',
  shop_product_5: 'Genshin Keqing Thunderclap figure',
  shop_product_6: 'Arknights Rhodes Island tactical backpack',

  // ============================================================================
  // [search]
  // ============================================================================
  search_action: 'Search',
  search_placeholder: '180 billion lost in 10 years... why?',
  search_hot_title: 'bilibili trending',
  search_full_list: 'Full list',
  search_tag_new: 'New',
  search_tag_hot: 'Hot',
  search_tag_meme: 'Meme',
  search_history: 'Search history',
  search_discovery: 'Discover',
  search_tab_comprehensive: 'Comprehensive',
  search_tab_anime: 'Anime',
  search_tab_live: 'Live',
  search_tab_user: 'Users',
  search_tab_movie: 'Movies & TV',
  search_tab_article: 'Articles',
  search_participating: '{n} participating',
  search_mock_participants: '12K',
  search_score_suffix: '',
  search_produce_badge: 'Official',
  search_region_cn: 'Mainland China',
  search_tags_anime: 'Original / Action / Fantasy',
  search_tags_movie: 'Drama / Adventure / Sci-fi',
  search_watch_now: 'Watch now',
  search_follow_anime: 'Follow anime',
  search_following_anime: 'Following anime',
  search_follow_drama: 'Follow drama',
  search_following_drama: 'Following drama',
  search_fans_count: '{n} followers',
  search_videos_count: '{n} videos',
  search_up_desc: 'Notable bilibili creator',
  search_view_all_videos: 'View all {n} videos',
  search_chip_all: 'All',
  search_chip_movie: 'Movies',
  search_chip_song: 'Songs',
  search_chip_nexus: 'Nexus',
  search_chip_yan: 'Yan Shuangying',
  search_empty_anime: 'No matching anime found',
  search_empty_movie: 'No matching movies or TV found',
  search_empty_user: 'No matching users found',
  search_empty_video: 'No matching videos found',

  // ============================================================================
  // [video]
  // ============================================================================
  video_tab_intro: 'Info',
  video_tab_comments: 'Comments',
  video_send_danmaku: 'Send a danmaku',
  video_danmaku_glyph: 'D',
  video_fans_count: '{n} followers',
  video_videos_count: '{n} videos',
  video_watching_count: '{n} watching',
  video_no_reprint: 'Reposting without permission is prohibited',
  video_ad_promo: 'Stuck on a problem? Ask Qianwen',
  video_ad_meta: 'Ad · 228K views',
  video_interested: 'You may also like',
  video_related: 'Related videos',
  video_related_meta: '{a} views · {b} danmaku',
  action_like: 'Like',
  action_dislike: 'Dislike',
  action_coin: 'Coin',
  action_fav: 'Favorite',
  action_share: 'Share',
  video_play: 'Play',
  video_pause: 'Pause',
  video_fullscreen: 'Full screen',
  comment_expand: 'Expand',
  comment_collapse: 'Collapse',
  comment_reply: 'Reply',
  comment_reply_count: '{n} replies',
  comment_hot: 'Top comments',
  comment_new: 'Latest comments',
  comment_sort_hot: 'By popularity',
  comment_sort_time: 'By time',
  comment_empty: 'No comments yet',
  comment_placeholder: 'Share your thoughts in a comment',
  vip_glyph: 'V',
  coin_glyph: 'C',
  coin_one: '1 coin',
  coin_two: '2 coins',
  coin_submit_hint: 'Swipe up or tap 22-chan to give coins',
  coin_balance: 'Coin balance: {n}',
  coin_also_like: 'Also like this video',
  coin_how: 'How do I earn coins?',
  coin_success: 'Coins added',
  mascot_alt: '22-chan',

  toast_coin_limit: "Coin failed — you've hit the coin limit for this video",
  toast_coin_insufficient: 'Not enough coins',
  toast_coin_insufficient_like: 'Not enough coins — liked and saved only',
  toast_triple_success: 'Liked, coined, and saved',
  user_fallback_name: 'User {mid}',

  // ============================================================================
  // [following]
  // ============================================================================
  following_title: 'Following',
  following_tab_all: 'All',
  following_tab_video: 'Videos',
  following_most_visited: 'Most visited',
  following_more: 'More',
  following_anime_updates: 'My anime & drama updates',
  following_view_all: 'View all',
  following_uploaded_video: 'uploaded a video',
  following_episode_update: 'Episode {n} now available',
  following_empty_title: 'You are not following any creators yet',
  following_empty_desc: 'Follow more creators so you never miss great content.',
  following_recommended: 'Creators you may like',
  following_recommended_up: 'Recommended creator',

  // ============================================================================
  // [me]
  // ============================================================================
  me_challenge: 'Take the membership quiz',
  me_set_nickname: 'Tap to set a nickname',
  me_vip: 'Premium',
  me_regular_member: 'Member',
  me_b_coins: 'B-coins',
  me_coins: 'Coins',
  me_space: 'Profile',
  me_dynamics: 'Posts',
  me_following: 'Following',
  me_fans: 'Followers',
  me_upgrade_vip: 'Go Premium',
  me_vip_center: 'Premium Center',
  me_vip_desc: 'Unlock exclusive offline perks',
  me_offline: 'Offline cache',
  me_history: 'History',
  me_favorites: 'Favorites',
  me_watch_later: 'Watch Later',
  me_creator_title: 'Post your first video',
  me_creator_desc: 'Unlock a limited avatar accessory and earn event rewards',
  me_creator_action: 'Reward Post',
  me_my_services: 'My Services',
  me_courses: 'My Courses',
  me_data_free: 'Zero-data Service',
  me_dress_up: 'Themes',
  me_wallet: 'My Wallet',
  me_games: 'Game Center',
  me_shop_orders: 'Shop Orders',
  me_lives: 'My Live',
  me_manga: 'Comics',
  me_promote: 'Boost Traffic',
  me_create_center: 'Creator Center',
  me_community: 'Community',
  me_charity: 'Charity',
  me_energy: 'Energy Station',
  me_coupons: 'Dimensional Coupons',
  me_report: 'Year in Review',
  me_more_services: 'More Services',
  me_contact: 'Contact Support',
  me_audio: 'Audio Mode',
  me_guardian: 'Minor Protection',
  me_settings: 'Settings',

  // ============================================================================
  // [space]
  // ============================================================================
  space_tab_home: 'Home',
  space_tab_works: 'Uploads',
  space_tab_fav: 'Favorites',
  space_tab_anime: 'Anime',
  space_edit_profile: 'Edit profile',
  space_vip_badge: 'Premium',
  space_fan_medal: 'Fan medal',
  space_achieve_medal: 'Achievements',
  space_detail: 'Details',
  space_collapse: 'Collapse',
  space_sign_fallback: 'Hi',
  space_add_school: 'Add school info',
  space_fav_section: 'Favorites',
  space_anime_section: 'Anime',
  space_chasing: 'Watching',
  space_publish_first: 'Post your first video to claim newcomer rewards',
  space_upload_btn: 'Upload now',
  space_creator_reward: 'Claim rewards at Creator Center',
  space_my_folders: 'My folders',
  space_my_subscriptions: 'My favorites & subscriptions',
  recent_likes_title: 'Recently liked videos',
  recent_likes_end: "╮( 3 )╭  That's everything",

  // ============================================================================
  // [up]
  // ============================================================================
  up_loading: 'Loading user info...',
  up_tab_home: 'Home',
  up_tab_dynamic: 'Posts',
  up_tab_works: 'Uploads',
  up_tab_shop: 'Store',
  up_verify_prefix: 'bilibili creator verification: ',
  up_not_live: 'They are not live right now — subscribe to their livestream',
  up_videos_section: 'Videos',
  up_uploaded_video: 'uploaded a video',
  up_sort_latest: 'Latest',
  up_no_goods: 'No products yet',

  // ============================================================================
  // [relation]
  // ============================================================================
  rel_title: 'My friends',
  rel_tab_follow: 'Following',
  rel_tab_fans: 'Followers',
  rel_search_follow: 'Search my following',
  rel_search_fans: 'Search my followers',
  rel_my_follow: 'My following',
  rel_my_fans: 'My followers',
  rel_count_people: '{n}',
  rel_recent_visit: 'Recently visited',
  rel_empty_follow: 'No following yet',
  rel_empty_fans: 'No followers yet',

  // ============================================================================
  // [fav]
  // ============================================================================
  fav_title: 'Favorites',
  fav_chase: 'Updates',
  fav_tab_folders: 'Folders',
  fav_tab_all: 'All',
  fav_tab_video: 'Videos',
  fav_tab_article: 'Articles',
  fav_empty: 'Nothing saved yet',
  fav_empty_article: 'No saved articles yet',
  fav_folder_default: 'Folder',
  fav_folder_creator: 'Created by {name}',
  fav_detail_creator: 'Created by {name}',
  fav_folder_empty: 'This folder is empty',
  fav_no_cover: 'No cover',
  fav_added_default: 'Added to "Default folder"',
  fav_modify: 'Change folder',
  fav_watch_later: 'Add to Watch Later',
  fav_choose_folder: 'Choose a folder',
  fav_new_folder: 'New folder',
  fav_create_title: 'Create',
  fav_create_cover: 'Cover',
  fav_create_name: 'Name',
  fav_create_name_placeholder: 'Name',
  fav_create_desc: 'Description',
  fav_create_desc_placeholder: 'Add a description (optional)',
  fav_create_public: 'Public',

  // ============================================================================
  // [ranking]
  // ============================================================================
  ranking_title: 'All rankings',
  ranking_danmaku_count: '{n} danmaku',
  ranking_bili_prefix: 'bilibili {p}',
  ranking_no_cover: 'No cover',
  ranking_empty: 'No data yet',

  // ============================================================================
  // [partitions]
  // ============================================================================
  partitions_title: 'Categories',
  partitions_quick: 'Quick access',
  partitions_edit: 'Edit',
  partitions_all: 'All categories',
  partitions_recommend: 'Recommended & services',
  partition_fallback: 'Category',
  partition_empty: 'No related videos yet',

  // ============================================================================
  // [profile]
  // ============================================================================
  pe_title: 'Account profile',
  pe_avatar: 'Avatar',
  pe_nickname: 'Nickname',
  pe_gender: 'Gender',
  pe_birthday: 'Birthday',
  pe_birthday_hint: 'Get wishes on your birthday',
  pe_sign: 'Bio',
  pe_sign_hint: 'This user is mysterious and left nothing here',
  pe_school: 'School',
  pe_school_hint: 'Add your school to find more alumni',
  pe_pendant: 'Avatar pendant',
  pe_qr: 'QR name card',
  pe_auth: 'Bilibili verification',
  gender_male: 'Male',
  gender_female: 'Female',
  gender_secret: 'Prefer not to say',
  pe_name_title: 'Edit nickname',
  pe_name_placeholder: 'Enter a new nickname',
  pe_name_cost: 'Changing your nickname costs 6 coins',
  pe_sign_title: 'Edit bio',
  pe_sign_placeholder: 'Enter a new bio',

  // ============================================================================
  // [school]
  // ============================================================================
  school_title: 'School info',
  school_select: 'Select school',
  school_year: 'Enrollment year',
  school_year_optional: 'Optional',
  school_edit_limit: 'Can only be changed once every 30 days',
  school_delete: 'Remove school info',
  school_search_placeholder: 'Search schools',
  school_success: 'You have joined the {school} campus',
  school_invite: 'Invite more alumni',

  // ============================================================================
  // [vip]
  // ============================================================================
  vip_title: 'Get Premium',
  vip_expire: 'Premium valid until {date}',
  vip_not_vip: 'You are not Premium yet — join for more perks ①',
  vip_device_scope: 'Works on phone, PC, and Pad',
  vip_switch_plan: 'Switch to standard plans ⇌',
  vip_pkg_year_auto: 'Yearly (auto-renew)',
  vip_pkg_year_super: 'Yearly Max (auto-renew)',
  vip_pkg_month_auto: 'Monthly (auto-renew)',
  vip_pkg_quarter_auto: 'Quarterly (auto-renew)',
  vip_pkg_quarter_super: 'Quarterly Max (auto-renew)',
  vip_badge_gift: 'Gift',
  vip_badge_flash: 'Limited offer',
  vip_discount: '¥{n} off',
  vip_gift_month: 'Includes a free month of Yanxuan Pro membership',
  vip_renew_note: 'Auto-renews at ¥{n}/month; cancel anytime',
  vip_voucher: 'Vouchers',
  vip_no_voucher: 'No voucher >',
  vip_use_prefix: 'Pay with',
  vip_joint: 'Bundled memberships',
  vip_see_more: 'See more >',
  vip_agreement: 'Please read the Premium Service Agreement and Auto-renewal Rules before subscribing',
  vip_confirm_pay: 'Agree and pay ¥{n}',
  vip_payment_title: 'Payment method',
  vip_alipay: 'Alipay',
  vip_wechat: 'WeChat Pay',
  vip_huabei: 'Huabei',
  vip_pay_agreement_desc: ', you agree to the Payment Authorization Agreement; renewal is charged 24h before expiry and can be cancelled anytime',
  vip_pay_agreement_full: 'By paying, you agree to the Payment Authorization Agreement; renewal is charged 24h before expiry and can be cancelled anytime',
  vip_select_wechat: 'Please choose WeChat Pay to try the full flow',

  // ============================================================================
  // [settings]
  // ============================================================================
  settings_title: 'Settings',
  settings_timer_off: 'Off',
  settings_timer_on: 'On',
  settings_sleep_on: 'Remind me',
  settings_sleep_off: 'No reminder',
  settings_account_profile: 'Account profile',
  settings_security: 'Security & privacy',
  settings_shipping: 'Shipping info',
  settings_language: 'Language',
  settings_splash: 'Launch screen',
  settings_recommend: 'Home recommendations',
  settings_recommend_subtitle: 'Double-column / autoplay on Wi-Fi or mobile data',
  settings_avatar_entry: 'Home avatar entry',
  settings_playback: 'Playback',
  settings_offline: 'Offline settings',
  settings_chase: 'Anime & drama settings',
  settings_push: 'Push notifications',
  settings_messages: 'Message settings',
  settings_harass: 'Harassment & interaction filters',
  settings_downloads: 'Download management',
  settings_storage: 'Clear storage',
  settings_other: 'Other settings',
  settings_timer: 'Sleep timer',
  settings_sleep: 'Sleep reminder',
  settings_dark: 'Dark mode',
  settings_support: 'Support',
  settings_about: 'About Bilibili',
  settings_business: 'Business inquiries',
  settings_terms: 'User Agreement',
  settings_privacy: 'Privacy Policy',
  settings_privacy_permissions: 'Privacy permissions',
  settings_collection_list: 'Personal info collection list',
  settings_sharing_list: 'Third-party sharing list',
  settings_basic_privacy: 'Bilibili basic feature privacy policy',
  settings_switch_account: 'Switch account',
  settings_logout: 'Sign out',

  opt_all: 'Everyone',
  opt_following: 'People I follow',
  opt_none: 'No notifications',
  opt_receive: 'Receive alerts',
  opt_never: 'Never',
  opt_receive_msg: 'Receive',
  opt_not_receive: "Don't receive",
  opt_on: 'On',
  opt_off: 'Off',

  // ============================================================================
  // [settings.push]
  // ============================================================================
  sp_title: 'Push notifications',
  sp_master: 'Master notification switch [On]',
  sp_master_sub: 'Change this in your device Settings > Notifications > Bilibili',
  sp_dnd: 'Do Not Disturb',
  sp_dnd_sub: 'No push notifications during Do Not Disturb hours',
  sp_sec_interact: 'Interactions',
  sp_like: 'Likes',
  sp_comment: 'Comments',
  sp_sec_pm: 'Direct messages',
  sp_chat: 'Chat messages',
  sp_sec_follow: 'Follows',
  sp_follow_up: 'Updates from creators you follow',
  sp_sec_content: 'Content recommendations',
  sp_recommend: 'Recommend content you may like',
  sp_hot: 'Trending',
  sp_activity: 'Events',
  sp_sec_sub: 'Subscriptions & reservations',
  sp_chase: 'Anime & drama update alerts',
  sp_live: 'Live alerts',
  sp_collection: 'Subscribed collection updates',
  sp_search: 'Saved search updates',
  sp_other_sub: 'Other subscription alerts',
  sp_sec_helper: 'Creator assistant',
  sp_upload: 'Upload service notifications',
  sp_sec_service: 'Service notifications',
  sp_logistics: 'Shipping & order notifications',
  sp_value: 'Value-added service notifications',
  sp_sec_other: 'Other notifications',
  sp_security: 'Account security notifications',
  sp_other: 'Other notifications',
  sp_sec_banner: 'In-app banners',
  sp_banner: 'In-app banner alerts',
  sp_banner_sub: 'Show push notifications while using the app',

  // ============================================================================
  // [settings.message]
  // ============================================================================
  sm_title: 'Message settings',
  sm_sec_notify: 'Message alerts',
  sm_notify: 'Message alerts',
  sm_notify_sub: 'When off, no badge counts on the home page',
  sm_sec_receive: 'Message receiving',
  sm_smart_block: 'Smart DM filtering',
  sm_smart_block_sub: 'Automatically blocks suspected harassment and spam',
  sm_block_words: 'Blocked words',
  sm_block_words_sub: 'Messages containing blocked words will be rejected',
  sm_sec_interact: 'Interactions',
  sm_reply_at: 'Replies & @',
  sm_reply_at_sub: 'Get notified about comments, danmaku, and more',
  sm_like: 'Likes received',
  sm_like_sub: 'Whether to receive like notifications',
  sm_fan: 'New followers',
  sm_fan_sub: 'Whether to receive new follower notifications',
  sm_sec_support: 'Fan clubs & non-followers',
  sm_support: 'Fan club messages',
  sm_unfollow: 'Messages from non-followers',
  sm_sec_contacts: 'Contacts',
  sm_blacklist: 'Block list',
  smr_title: 'Replies & @ alerts',
  sml_title: 'Like alerts',
  smf_title: 'New follower alerts',

  // ============================================================================
  // [settings.harass]
  // ============================================================================
  sh_title: 'Harassment & interaction filters',
  sh_sec_short: 'Short-term protection',
  sh_onekey: 'One-tap anti-harassment',
  sh_onekey_sub: 'For a limited time, only receive DMs, danmaku, and comments from selected groups, and stop receiving @ mentions.',
  sh_sec_long: 'Long-term protection',
  sh_comment: 'Who can comment',
  sh_danmaku: 'Who can send danmaku',
  sh_pm: 'Who can DM me',
  sh_opt_7days: 'People following me for 7+ days',
  sh_opt_following: 'People I follow',

  // ============================================================================
  // [settings.recommend]
  // ============================================================================
  sr_title: 'Home recommendations',
  sr_sec_mode: 'Home video playback mode',
  sr_portrait: 'Portrait mode',
  sr_portrait_sub: 'Play videos in portrait mode by default',
  sr_auto: 'Auto mode',
  sr_auto_sub: 'Choose playback mode based on video type',
  sr_sec_autoplay: 'Home autoplay',
  sr_opt_all: 'Autoplay on Wi-Fi / zero-rated / mobile data',
  sr_opt_wifi: 'Autoplay on Wi-Fi only',
  sr_opt_off: 'Autoplay off',
  sr_sec_sound: 'Large card default sound (takes effect after restart)',
  sr_sound_on: 'Sound on',
  sr_sound_off: 'Muted',
  sr_sec_refresh: 'Auto-refresh recommendations',
  sr_column: 'Single/double column layout',

  // ============================================================================
  // [settings.storage]
  // ============================================================================
  st_title: 'Clear storage',
  st_base: 'App base component library',
  st_image: 'Image cache & message history',
  st_other: 'Other cache files',
  st_account: 'Account & login info',
  st_offline: 'Offline video files',
  st_webview: 'WebView cache files',
  st_game: 'Game pre-download packages',
  st_clean: 'Clean selected items',

  // ============================================================================
  // [settings.playback]
  // ============================================================================
  spb_title: 'Playback',
  spb_autoplay: 'Autoplay settings',
  spb_portrait: 'Portrait mode settings',
  spb_pip: 'Mini player & background audio',
  spb_danmaku: 'Danmaku & subtitles',
  spb_quality: 'Video quality',
  spb_other: 'Other settings',
  spa_data: 'Autoplay on mobile data',
  spa_detail: 'Play immediately on detail page',
  spa_detail_sub: 'Autoplay videos when opening the detail page',
  spa_fullscreen: 'Full screen on detail page',
  spa_fullscreen_sub: 'Autoplay in full screen when opening the detail page',
  spa_feed: 'Autoplay single-column videos in feeds',
  spa_feed_sub: 'Autoplay on',
  spa_home: 'Home autoplay',
  saf_hint: 'This affects video playback in all list views',
  saf_opt_on: 'Autoplay on',
  saf_opt_wifi: 'Autoplay on Wi-Fi / zero-rated only',
  spp_label: 'Play portrait videos full screen in portrait mode',
  spp_sub: 'Swipe up and down between videos in full screen',
  pip_sec_pip: 'Mini player',
  pip_out: 'Auto mini player outside the app',
  pip_out_sub: 'Keep playing in a mini window when you leave the app',
  pip_in: 'Auto mini player inside the app',
  pip_in_sub: 'Keep playing in a mini window when you switch pages',
  pip_size: 'Default mini player size',
  pip_size_sub: 'Double-tap the mini player to resize',
  pip_sec_bg: 'Background audio',
  pip_bg: 'Background audio',
  pip_bg_sub: 'Keep playing audio when locked or in the background',
  pip_bg_series: 'Auto-play related videos in background audio mode',
  sd_sec_danmaku: 'Danmaku',
  sd_memory: 'Remember danmaku toggle state',
  sd_memory_sub: 'Danmaku toggle changes sync to all videos on this device',
  sd_quick: 'Quick danmaku actions',
  sd_quick_sub: 'Tap a danmaku to like, copy, and more',
  sd_sec_subtitle: 'Subtitles',
  sd_feedback: 'Subtitle feedback mode',
  sd_feedback_sub: 'Tap subtitles to send feedback',
  sd_drag: 'Draggable subtitles',
  sd_drag_sub: 'Drag subtitles to reposition them',
  sq_hdr: 'Prefer HDR quality',
  sq_hdr_sub: 'Preferred for Premium members on supported devices',
  spo_fullscreen_count: 'Show concurrent viewers in full screen',
  spo_gravity: 'Rotate with gravity sensor',
  spo_gravity_sub: 'Switch between half/full screen by rotating the device',
  spo_sec_volume: 'Volume leveling',
  spo_vol_standard: 'Standard mode',
  spo_vol_standard_sub: 'Automatically balance volume across videos',
  spo_vol_high: 'High dynamic mode',
  spo_vol_high_sub: 'Keeps more audio detail at a lower volume',
  spo_eye: 'Eye comfort mode',
  spo_color: 'Color vision assistance',
  spo_https: 'Use HTTPS playback',
  spo_https_sub: 'More secure',

  // ============================================================================
  // [settings.avatarEntry]
  // ============================================================================
  sa_title: 'Home avatar entry',
  sa_sec_jump: 'Home avatar entry destination',
  sa_recent: 'Recent / Watch / Listen',
  sa_recent_sub: 'Tap the home avatar to open Recent and more',
  sa_watch: 'Watch videos',
  sa_watch_sub: 'Hide the watch entry when off',
  sa_listen: 'Listen to videos',
  sa_listen_sub: 'Hide the listen entry when off',
  sa_me: 'Me',
  sa_me_sub: 'Tap the home avatar to open the Me page',
  sa_sec_quick: 'Recent page shortcuts',
  sa_offline: 'Offline cache',
  sa_history: 'History',
  sa_fav: 'Favorites',
  sa_later: 'Watch Later',
  sa_add: 'Add',

  // ============================================================================
  // [settings.misc]
  // ============================================================================
  sc_title: 'Anime & drama settings',
  sc_xianxiu: 'Night-owl mode',
  sc_xianxiu_sub: 'Anime airing between 0:00-6:00 shows on the previous day',
  sc_sec_preview: 'Night-owl mode preview',
  sc_preview_hint: 'Night-owl mode shows next-day 0:00-6:00 anime',
  so_title: 'Offline settings',
  so_auto: 'Auto download',
  so_auto_sub: 'Automatically resume unfinished downloads',
  so_diagnosis: 'Offline diagnostics',
  so_sdcard: 'External SD card test',
  sl_title: 'Language',
  sl_sec: 'App language',
  ssu_title: 'Fan clubs',
  ssu_receive: 'Receive fan club messages',
  ssu_receive_sub: 'Fan club message alerts',
  ssu_collapse: 'Collapse fan club messages',
  ssu_collapse_sub: 'Fan club messages will be folded into My Fan Clubs',
  ssu_sec_guide: 'Fan club guide',
  ssu_join: 'How to join a fan club',
  sun_title: 'Messages from non-followers',
  sun_sec: 'Non-follower message alerts',
  sun_collapse: 'Collapse non-follower messages',
  sun_collapse_sub: 'Messages from non-followers will be folded together',
  sti_title: 'Sleep timer',
  sti_hint: "You'll be reminded when the timer ends",
  sti_off: 'Off',
  sti_15: '15 minutes',
  sti_30: '30 minutes',
  sti_60: '60 minutes',
  sti_custom: 'Custom',
  ssl_title: 'Sleep reminder',
  ssl_label: 'Sleep reminder',
  ssl_sub: 'Get a reminder at bedtime',
  sw_title: 'Image watermark',
  sw_hint: 'Adds a watermark to images posted in feeds and comments',
  sw_off: 'Off',
  sw_center: 'Center of image',
  sw_br: 'Bottom-right corner',
  si_title: 'Default image quality',
  si_clear: 'Clear',
  si_clear_sub: 'Clear (higher quality, sharper images)',
  si_normal: 'Standard',
  si_normal_sub: 'Standard (less data, faster loading)',
  si_auto: 'Auto',
  si_auto_sub: 'Auto (clear on Wi-Fi, standard on mobile data)',
  sot_title: 'Other settings',
  sot_wifi_pkg: 'Auto-prepare installer on Wi-Fi',
  sot_wifi_pkg_sub: 'Download the latest installer automatically on Wi-Fi',
  sot_clipboard: 'Clipboard auto-jump',
  sot_clipboard_sub: 'Jump to copied content automatically',
  sot_screenshot: 'Quick screenshot sharing',
  sot_screenshot_sub: 'When off, no quick-share prompt appears after screenshots on video or post pages.',
};
